swagger: "2.0"
info:
  version: "0.0.1"
  title: Spotin App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /users:
    # our controller name
    x-swagger-router-controller: users
    get:
      description: get a list of all users
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetUsersListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: add a new user
      parameters:
        - name: user
          description: User properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetUserResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/{id}:
    # our controller name
    x-swagger-router-controller: user
    get:
      description: get a given user by id
      # define the type of response for Success "200" and Error
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetUserResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: modify user
      parameters:
        - name: user
          description: User properties to change
          in: body
          required: true
          schema:
            $ref: "#/definitions/UserModify"
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetUserResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: delete user
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetUserResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /businesses:
    # our controller name
    x-swagger-router-controller: business
    get:
      description: get a list of all businesses
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetBusinessesListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: add a new business
      parameters:
        - name: business
          description: Business properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Business"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetBusinessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  # responses
  GetUsersListResponse:
      properties:
        # The array of movies
        users:
          type: array
          items: 
            type: object
            properties:
              id:
                type: string
              username:
                type: string
              email:
                type: string
              password:
                type: string
              display_name:
                type: string
              phone_number:
                type: string
  GetUserResponse:
      type: object
      properties:
          id:
            type: string
          username:
            type: string
          email:
            type: string
          password:
            type: string
          display_name:
            type: string
          phone_number:
            type: string
  GetBusinessesListResponse:
      properties:
        # The array of movies
        businesses:
          type: array
          items: 
            $ref: "#/definitions/Business"
                      
  GetBusinessResponse:
      $ref: "#/definitions/Business"
     
  ErrorResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      description:
        type: string
        description: a short comment 
    required:
      - success
      - description
  # parameter schemas
  Business:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        location:
          type: object
          properties:
            address:
              type: string
            location:
              type: string
        days_of_operation:
          type: object
          properties:
            days:
              type: string
            hours:
              type: string
        services:
          type: array
          items:
            type: object
            properties:
              headline:
                type: string
              price:
                type: string
              description:
                type: string
              discount:
                type: string
        reviews:
          type: array
          items:
            type: object
            properties:
              user:
                $ref: "#/definitions/User"
              comment:
                $ref: "#/definitions/Comment"
        images:
          type: array
          items:
            type: object
            properties:
              image:
                $ref: "#/definitions/Image"
  User:
    type: object
    properties:
      username:
        type: string
        description: designated user name
      email:
        type: string
        description: designated user's email address
      password:
        type: string
        description: designated user's password
      display_name:
        type: string
        description: designated user's display name (optional)
      phone_number:
        type: string
        description: designated user's phone number (optional)
    required:
      - username
      - email
      - password
  UserModify:
    type: object
    properties:
      username:
        type: string
        description: designated user name
      email:
        type: string
        description: designated user's email address
      password:
        type: string
        description: designated user's password
      display_name:
        type: string
        description: designated user's display name
      phone_number:
        type: string
        description: designated user's phone number
  Comment:
    type: object
    properties:
      headline:
        type: string
        description: designated user name
      comment:
        type: string
        description: designated user name
      score:
        type: number
        description: designated user name
  Image:
    type: object
    properties:
      image:
        type: string
        format: byte
      likes:
        type: number